### ISSUE TITLE
Add note about legacy object-literal decorators?

### ISSUE THREAD

**Issue by davidtaylorhq** [ef4/decorator-transforms#12]
The README currently says 

> As far as I can tell, it does implement the complete API surface of ['@babel/plugin-proposal-decorators', { legacy: true }]

However, it doesn't look like this transform supports object literal function decorators as defined by the ['legacy stage one'](https://github.com/wycats/javascript-decorators/blob/e1bf8d41bfa2591d949dd3bbf013514c8904b913/README.md#object-literal-method-declaration) proposal.

At Discourse, we have a *lot* of these decorators on object-literal properties. We are working towards removing these in favour of native classes and their more-modern decorators. But in the meantime it looks like we won't be able to use this new decorator-transforms babel plugin.

I don't expect you'll want to add support for these mega-legacy decorators. But it might be worth adding a note about it to the README - I doubt Discourse is the only Ember app to be relying on this old syntax.

**Comment by ef4** [comment]
Oh I think that's worth adding. The only point of this package is to match legacy decorators bug-for-bug.

**Comment by ef4** [comment]
Please try 1.1.0 and let me know if anything else is inconsistent with the old behaviors.
