### ISSUE TITLE
Side-effecting getters using Object.defineProperty to erase decorated fields do not define the property on the subclass

### ISSUE THREAD

**Issue by NullVoxPopuli** [ef4/decorator-transforms#7]
Reproduction: https://stackblitz.com/edit/stackblitz-starters-fsujfm?file=README.md

There are two commands to run:
- `npm start` - uses decorator-transforms
- `npm run start:official-plugins` - uses traditional 8 plugin approach

What's expected?
- in the console, we should see 3 properties logged: `foo`, `bar`, and `overrideMe`, 
- but in the `decorator-transforms` demo (`npm start`), the decorated fields from the super class are missing

It's _totally possible_, that the original code is bugged.

In the real code, I'm looking at exploring make the decorators more normal, and statically replace their descriptors rather than dynamically defineProperty -- since getters are already lazy, and I think laziness was the original intent.

**Comment by ef4** [comment]
In the stackblitz, I see `['bar', 'overrideMe']` for *both* commands. `npm run start` and `npm run start:official-plugins`. So I don't think this reproduces a difference.

**Comment by NullVoxPopuli** [comment]
bah, I halluc. I'll keep digging
